import { operations } from '../core/operations.ts';
import { buildToolDefs } from '../mcp/tool-defs.ts';

/**
 * `gbrain --tools-json` — the public CLI tool-catalog contract.
 *
 * The legacy keys (`name`, `description`, `parameters` with the compact
 * `"type"` / `"type?"` strings) are preserved VERBATIM — downstream scripts
 * parse them. WP3 adds the full JSON Schema (param descriptions, enums,
 * defaults, required array) additively under a new `schema` key per tool,
 * generated by the same buildToolDefs mapper the MCP transports serve.
 */
export function printToolsJson() {
  const defsByName = new Map(buildToolDefs(operations).map(def => [def.name, def]));
  const tools = operations.map(op => ({
    name: op.name,
    description: op.description,
    parameters: Object.fromEntries(
      Object.entries(op.params).map(([k, v]) => [
        k,
        `${v.type}${v.required ? '' : '?'}`,
      ]),
    ),
    schema: defsByName.get(op.name)!.inputSchema,
  }));

  console.log(JSON.stringify(tools, null, 2));
}
